# .github/workflows/ci-dev.yml
name: CI on Pull Request to dev

on:
  pull_request:
    branches: [dev]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run integration tests
        run: |
          pytest backend/tests/test_integration.py
