name: Push to Staging

on:
  push:
    branches: [dev]

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Push to staging
        run: |
          git fetch origin
          git checkout -B staging
          git merge origin/dev --no-edit
          git push origin staging
