# .github/workflows/push-to-staging.yml
name: Push to Staging

on:
  push:
    branches: [dev]

jobs:
  promote-to-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Push changes to staging
        run: |
          git fetch origin
          git checkout staging
          git merge dev --no-edit
          git push origin staging
